import { NextRequest, NextResponse } from "next/server";

const BACKEND = process.env.BACKEND_URL;

const PROFILES: Record<string, any> = {
  RELIANCE: { symbol: "RELIANCE", name: "Reliance Industries Ltd", sector: "Energy", industry: "Oil, Gas & Diversified", founded: 1966, employees: 236334, ceo: "Mukesh D. Ambani", hq: "Mumbai, Maharashtra", description: "Reliance Industries is India's largest company by market cap, spanning energy, petrochemicals, retail (JioMart), and telecom (Jio). It operates the world's largest oil refinery complex at Jamnagar.", market_cap: 19200000000000, risk_score: 32, fraud_score: 8, sentiment_score: 42, esg_score: 58, pe_ratio: 27.4, pb_ratio: 2.9, roe: 10.8, debt_equity: 0.34, promoter_holding: 50.33, fii_holding: 22.41, dii_holding: 15.67, public_holding: 11.59 },
  TCS: { symbol: "TCS", name: "Tata Consultancy Services Ltd", sector: "IT", industry: "IT Services & Consulting", founded: 1968, employees: 601546, ceo: "K Krithivasan", hq: "Mumbai, Maharashtra", description: "TCS is India's largest IT services company and the second most valuable company, serving clients across BFSI, retail, manufacturing and more in 50+ countries.", market_cap: 13500000000000, risk_score: 21, fraud_score: 5, sentiment_score: 18, esg_score: 72, pe_ratio: 29.8, pb_ratio: 13.2, roe: 49.7, debt_equity: 0.0, promoter_holding: 72.19, fii_holding: 13.52, dii_holding: 8.34, public_holding: 5.95 },
  HDFCBANK: { symbol: "HDFCBANK", name: "HDFC Bank Ltd", sector: "Banking", industry: "Private Sector Banking", founded: 1994, employees: 213527, ceo: "Sashidhar Jagdishan", hq: "Mumbai, Maharashtra", description: "HDFC Bank is India's largest private sector bank with a network of 8,700+ branches. Post HDFC Ltd merger, it is also one of the largest financial conglomerates in India.", market_cap: 12100000000000, risk_score: 38, fraud_score: 9, sentiment_score: 35, esg_score: 65, pe_ratio: 18.4, pb_ratio: 2.5, roe: 16.8, debt_equity: 6.1, promoter_holding: 0.0, fii_holding: 53.82, dii_holding: 25.41, public_holding: 20.77 },
  INFY: { symbol: "INFY", name: "Infosys Ltd", sector: "IT", industry: "IT Services & Consulting", founded: 1981, employees: 317240, ceo: "Salil Parekh", hq: "Bengaluru, Karnataka", description: "Infosys is a global leader in IT services, consulting and outsourcing with 300+ clients across 50 countries. Known for its digital transformation, cloud and AI capabilities.", market_cap: 7200000000000, risk_score: 25, fraud_score: 6, sentiment_score: 22, esg_score: 78, pe_ratio: 24.6, pb_ratio: 7.8, roe: 32.4, debt_equity: 0.0, promoter_holding: 14.87, fii_holding: 33.28, dii_holding: 31.45, public_holding: 20.40 },
  TATAMOTORS: { symbol: "TATAMOTORS", name: "Tata Motors Ltd", sector: "Automobiles", industry: "Automobiles & Auto Components", founded: 1945, employees: 83625, ceo: "Shailesh Chandra (India) / Adrian Mardell (JLR)", hq: "Mumbai, Maharashtra", description: "Tata Motors is India's largest automobile manufacturer. It owns Jaguar Land Rover (JLR) globally and is aggressively expanding its EV portfolio in India with Nexon EV and Punch EV.", market_cap: 3250000000000, risk_score: 62, fraud_score: 15, sentiment_score: 55, esg_score: 51, pe_ratio: 9.2, pb_ratio: 2.8, roe: 30.5, debt_equity: 1.45, promoter_holding: 42.58, fii_holding: 22.67, dii_holding: 18.44, public_holding: 16.31 },
  BAJFINANCE: { symbol: "BAJFINANCE", name: "Bajaj Finance Ltd", sector: "NBFC", industry: "Non-Banking Financial Company", founded: 1987, employees: 39701, ceo: "Rajeev Jain", hq: "Pune, Maharashtra", description: "Bajaj Finance is India's largest NBFC with 80M+ customers across consumer lending, SME finance, mortgages and insurance distribution. Known for best-in-class underwriting and collections.", market_cap: 4520000000000, risk_score: 45, fraud_score: 11, sentiment_score: 30, esg_score: 60, pe_ratio: 32.1, pb_ratio: 6.4, roe: 22.8, debt_equity: 3.8, promoter_holding: 54.78, fii_holding: 18.92, dii_holding: 16.14, public_holding: 10.16 },
  ICICIBANK: { symbol: "ICICIBANK", name: "ICICI Bank Ltd", sector: "Banking", industry: "Private Sector Banking", founded: 1994, employees: 130473, ceo: "Sandeep Bakhshi", hq: "Mumbai, Maharashtra", description: "ICICI Bank is India's second largest private sector bank with strong retail and corporate banking franchise. Known for iMobile app and aggressive digital banking push.", market_cap: 8150000000000, risk_score: 35, fraud_score: 8, sentiment_score: 28, esg_score: 63, pe_ratio: 16.8, pb_ratio: 3.0, roe: 18.4, debt_equity: 5.4, promoter_holding: 0.0, fii_holding: 46.91, dii_holding: 38.24, public_holding: 14.85 },
  WIPRO: { symbol: "WIPRO", name: "Wipro Ltd", sector: "IT", industry: "IT Services & Consulting", founded: 1945, employees: 234054, ceo: "Srinivas Pallia", hq: "Bengaluru, Karnataka", description: "Wipro is a leading global information technology, consulting and business process services company. It serves clients across 60+ countries with focus on technology transformation.", market_cap: 2920000000000, risk_score: 29, fraud_score: 7, sentiment_score: 20, esg_score: 70, pe_ratio: 21.3, pb_ratio: 3.8, roe: 17.2, debt_equity: 0.0, promoter_holding: 72.93, fii_holding: 7.52, dii_holding: 12.38, public_holding: 7.17 },
  SBIN: { symbol: "SBIN", name: "State Bank of India", sector: "Banking", industry: "Public Sector Banking", founded: 1955, employees: 232296, ceo: "Challa Sreenivasulu Setty", hq: "Mumbai, Maharashtra", description: "SBI is India's largest public sector bank with 22,000+ branches and 65,000+ ATMs. It commands ~25% market share in Indian banking and has recently improved asset quality significantly.", market_cap: 7120000000000, risk_score: 42, fraud_score: 12, sentiment_score: 38, esg_score: 55, pe_ratio: 10.4, pb_ratio: 1.6, roe: 17.5, debt_equity: 12.1, promoter_holding: 57.49, fii_holding: 11.79, dii_holding: 24.13, public_holding: 6.59 },
  MARUTI: { symbol: "MARUTI", name: "Maruti Suzuki India Ltd", sector: "Automobiles", industry: "Passenger Vehicles", founded: 1981, employees: 21197, ceo: "Hisashi Takeuchi", hq: "New Delhi", description: "Maruti Suzuki is India's largest passenger car maker with ~42% market share. Strong distribution network of 3,500+ outlets and a dominant position in entry/mid-size segment.", market_cap: 4210000000000, risk_score: 28, fraud_score: 6, sentiment_score: 24, esg_score: 68, pe_ratio: 28.5, pb_ratio: 5.2, roe: 19.4, debt_equity: 0.0, promoter_holding: 58.19, fii_holding: 21.43, dii_holding: 12.86, public_holding: 7.52 },
  ASIANPAINT: { symbol: "ASIANPAINT", name: "Asian Paints Ltd", sector: "Consumer Goods", industry: "Paints & Coatings", founded: 1942, employees: 8000, ceo: "Amit Syngle", hq: "Mumbai", description: "Asian Paints is India's largest paint company and 4th largest decorative paints company globally with presence in 15 countries.", market_cap: 2950000000000, risk_score: 24, fraud_score: 4, sentiment_score: 15, esg_score: 74, pe_ratio: 52.3, pb_ratio: 14.8, roe: 30.2, debt_equity: 0.05, promoter_holding: 52.63, fii_holding: 19.24, dii_holding: 20.47, public_holding: 7.66 },
  SUNPHARMA: { symbol: "SUNPHARMA", name: "Sun Pharmaceutical Industries Ltd", sector: "Pharma", industry: "Pharmaceuticals", founded: 1983, employees: 43000, ceo: "Dilip Shanghvi", hq: "Mumbai", description: "Sun Pharma is India's largest pharma company and the 4th largest specialty generic pharma company globally. Strong US generics and specialty franchise.", market_cap: 4340000000000, risk_score: 30, fraud_score: 7, sentiment_score: 20, esg_score: 64, pe_ratio: 35.8, pb_ratio: 6.2, roe: 17.3, debt_equity: 0.0, promoter_holding: 54.48, fii_holding: 18.92, dii_holding: 18.46, public_holding: 8.14 },
};

const DEFAULT_PROFILE = (symbol: string) => ({
  symbol, name: `${symbol} Ltd`, sector: "Diversified", industry: "Diversified", founded: 2000, employees: 5000,
  ceo: "Managing Director", hq: "Mumbai, Maharashtra", description: `${symbol} is a listed company on NSE/BSE.`,
  market_cap: 500000000000, risk_score: 40, fraud_score: 10, sentiment_score: 30, esg_score: 60,
  pe_ratio: 20, pb_ratio: 3, roe: 15, debt_equity: 0.5,
  promoter_holding: 50, fii_holding: 20, dii_holding: 20, public_holding: 10,
});

export async function GET(request: NextRequest, { params }: { params: Promise<{ symbol: string }> }) {
  const { symbol } = await params;
  const sym = symbol.toUpperCase();
  const auth = request.headers.get("Authorization") || "";
  const token = auth.replace("Bearer ", "");

  if (BACKEND && token && token !== "DEMO_TOKEN") {
    try {
      const res = await fetch(`${BACKEND}/api/v1/companies/${sym}`, { headers: { Authorization: auth } });
      if (res.ok) return NextResponse.json(await res.json());
    } catch { /* fall through */ }
  }
  return NextResponse.json(PROFILES[sym] || DEFAULT_PROFILE(sym));
}
